apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-cronjob-api
  labels:
    app: flask-k8s-cronjob-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-k8s-cronjob-api
  template:
    metadata:
      labels:
        app: flask-k8s-cronjob-api
    spec:
      serviceAccountName: flask-k8s-cronjob-api
      containers:
      - name: flask-k8s-cronjob-api
        image: flask-k8s-cronjob-api:latest
        ports:
        - containerPort: 5000
