apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-cronjob-api
spec:
  type: NodePort
  selector:
    app: flask-k8s-cronjob-api
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
